#include "../SMBIOS.TypeInfo.h"

#include <stdio.h>

static void PrintString(const char* Value)
{
    const unsigned char* p = (const unsigned char*)Value;

    putchar('"');
    while (*p != 0)
    {
        if (*p == '"' || *p == '\\')
        {
            putchar('\\');
        }
        putchar(*p++);
    }
    putchar('"');
}

int main(void)
{
    size_t TypeIndex;

    fputs("\xEF\xBB\xBF// Generated by GenerateSmbiosMetadata.c from SMBIOS.TypeInfo.h.\n", stdout);
    puts("// <auto-generated />");
    puts("#nullable enable");
    puts("");
    puts("using System;");
    puts("using System.Collections.Generic;");
    puts("");
    puts("namespace KNSoft.FirmwareSpec;");
    puts("");
    puts("internal static class SmbiosMetadata");
    puts("{");
    puts("    internal static readonly SmbiosTypeInfo?[] ByType = Create();");
    puts("");
    puts("    internal static readonly IReadOnlyList<SmbiosTypeInfo> All = Array.AsReadOnly(");
    puts("    [");
    for (TypeIndex = 0; TypeIndex < sizeof(SmbiosTypeInfo) / sizeof(SmbiosTypeInfo[0]); TypeIndex++)
    {
        printf("        ByType[%hhu]!,\n", SmbiosTypeInfo[TypeIndex].Type);
    }
    puts("    ]);");
    puts("");
    puts("    private static SmbiosTypeInfo?[] Create()");
    puts("    {");
    puts("        SmbiosTypeInfo?[] result = new SmbiosTypeInfo?[256];");
    for (TypeIndex = 0; TypeIndex < sizeof(SmbiosTypeInfo) / sizeof(SmbiosTypeInfo[0]); TypeIndex++)
    {
        const SMBIOS_TYPE_INFO* Type = &SmbiosTypeInfo[TypeIndex];
        const SMBIOS_FIELD_TYPE_INFO* Backing = NULL;
        size_t FieldIndex;

        printf("        result[%hhu] = new(%hhu, ", Type->Type, Type->Type);
        PrintString((const char*)Type->Name);
        puts(",");
        puts("        [");
        for (FieldIndex = 0; FieldIndex < Type->FieldCount; FieldIndex++)
        {
            const SMBIOS_FIELD_TYPE_INFO* Field = &Type->Fields[FieldIndex];
            size_t EnumIndex;

            if (!Field->IsBitField)
            {
                Backing = Field;
            } else if (Backing == NULL)
            {
                return 1;
            }
            puts("            new(");
            fputs("                ", stdout);
            PrintString((const char*)Field->Name);
            puts(",");
            printf("                %hu, %hhu, SmbiosDataType.%s, %hhu, %hhu,\n",
                   Field->IsBitField ? Backing->Offset : Field->Offset,
                   Field->IsBitField ? Backing->Size : Field->Size,
                   Field->Type == SmbiosDataTypeOther ? "Other" :
                   Field->Type == SmbiosDataTypeString ? "StringIndex" :
                   Field->Type == SmbiosDataTypeUInt ? "UnsignedInteger" :
                   Field->Type == SmbiosDataTypeBit ? "Bit" :
                   Field->Type == SmbiosDataTypeEnum ? "Enum" :
                   Field->Type == SmbiosDataTypeUuid ? "Uuid" : "Raw",
                   Field->IsBitField ? (BYTE)Field->Offset : 0,
                   Field->IsBitField ? Field->Size : 0);
            puts("                [");
            for (EnumIndex = 0; EnumIndex < Field->Enum.Count; EnumIndex++)
            {
                fputs("                    new(", stdout);
                PrintString((const char*)Field->Enum.Values[EnumIndex].Name);
                printf(", 0x%llXUL),\n", (unsigned long long)Field->Enum.Values[EnumIndex].Value);
            }
            puts("                ]),");
        }
        puts("        ]);");
    }
    puts("        return result;");
    puts("    }");
    puts("}");
    return 0;
}
