name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Build-Windows-MSVC:
    strategy:
      matrix:
        platform: [x64, x86, ARM64]
        config: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
          submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build
      working-directory: ${{github.workspace}}
      run: msbuild ".\VSProject\KNSoft.FirmwareSpec.sln" /restore /m /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}} /p:RestorePackagesConfig=true /p:RunCodeAnalysis=true /p:EnableCppCodeAnalysis=true /p:CodeAnalysisTreatWarningsAsErrors=true
    - name: Run sample programs
      if: ${{ matrix.platform == 'x64' || matrix.platform == 'x86' }}
      working-directory: ${{github.workspace}}
      run: |
        & .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\FirmwareSpecTest.exe
        & .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\AcpiDecode.exe >.\AcpiDecode.txt
        & .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\CpuidDecode.exe >.\CpuidDecode.txt
        & .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\SmbiosDecode.exe >.\SmbiosDecode.txt
        Get-Content .\AcpiDecode.txt
        Get-Content .\CpuidDecode.txt
        Get-Content .\SmbiosDecode.txt
    - name: Archive sample programs and outputs
      if: ${{ matrix.platform == 'x64' || matrix.platform == 'x86' }}
      uses: actions/upload-artifact@main
      with:
        name: KNSoft.FirmwareSpec-Windows-MSVC-${{matrix.platform}}-${{matrix.config}}-${{github.sha}}
        path: |
          .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\AcpiDecode.exe
          .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\CpuidDecode.exe
          .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\FirmwareSpecTest.exe
          .\VSProject\OutDir\${{matrix.platform}}\${{matrix.config}}\SmbiosDecode.exe
          .\AcpiDecode.txt
          .\CpuidDecode.txt
          .\SmbiosDecode.txt

  Build-Linux-GCC:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
          submodules: recursive
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        gcc -std=gnu2x -Wall -Wextra -Werror -fdiagnostics-color=always -g ./SmbiosDecode.c -o SmbiosDecode
        gcc -std=gnu2x -Wall -Wextra -Werror -fdiagnostics-color=always -g ./AcpiDecode.c -o AcpiDecode
        gcc -std=gnu2x -Wall -Wextra -Werror -fdiagnostics-color=always -g ./CpuidDecode.c -o CpuidDecode
        gcc -std=gnu2x -Wall -Wextra -Werror -fdiagnostics-color=always -g ./FirmwareSpecTest.c -o FirmwareSpecTest
    - name: Run sample programs
      working-directory: ${{github.workspace}}
      run: |
        ./FirmwareSpecTest
        sudo ./AcpiDecode >./AcpiDecode.txt
        ./CpuidDecode >./CpuidDecode.txt
        sudo ./SmbiosDecode >./SmbiosDecode.txt
        cat ./AcpiDecode.txt
        cat ./CpuidDecode.txt
        cat ./SmbiosDecode.txt
    - name: Archive sample programs and outputs
      uses: actions/upload-artifact@main
      with:
        name: KNSoft.FirmwareSpec-Linux-GCC-${{github.sha}}
        path: |
          ./AcpiDecode
          ./AcpiDecode.txt
          ./CpuidDecode
          ./CpuidDecode.txt
          ./FirmwareSpecTest
          ./SmbiosDecode
          ./SmbiosDecode.txt
